-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 01:12:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema motaflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema motaflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `motaflix` DEFAULT CHARACTER SET utf8 ;
USE `motaflix` ;

-- -----------------------------------------------------
-- Table `motaflix`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `release` DATE NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`parental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`parental` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `min_interval` INT NOT NULL,
  `max_interval` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `parental_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_parental1_idx` (`parental_id` ASC),
  CONSTRAINT `fk_user_parental1`
    FOREIGN KEY (`parental_id`)
    REFERENCES `motaflix`.`parental` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `acronym` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `birthday` DATE NOT NULL,
  `height` FLOAT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `motaflix`.`subtitle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`subtitle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subtitle_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_subtitle_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `media_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_media1_idx` (`media_id` ASC),
  INDEX `fk_rating_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_rating_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `motaflix`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`media_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`media_has_category` (
  `media_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `category_id`),
  INDEX `fk_media_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_media_has_category_media_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_has_category_media`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `motaflix`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`media_has_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`media_has_actor` (
  `media_id` INT NOT NULL,
  `actor_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `actor_id`),
  INDEX `fk_media_has_actor_actor1_idx` (`actor_id` ASC),
  INDEX `fk_media_has_actor_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_has_actor_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_actor_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `motaflix`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`media_has_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`media_has_language` (
  `media_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `language_id`),
  INDEX `fk_media_has_language_language1_idx` (`language_id` ASC),
  INDEX `fk_media_has_language_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_has_language_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `motaflix`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`media_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`media_has_genre` (
  `media_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `genre_id`),
  INDEX `fk_media_has_genre_genre1_idx` (`genre_id` ASC),
  INDEX `fk_media_has_genre_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_has_genre_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `motaflix`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `due` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_user1_idx` (`user_id` ASC),
  INDEX `fk_subscription_plan1_idx` (`plan_id` ASC),
  CONSTRAINT `fk_subscription_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `motaflix`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `motaflix`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorite_user1_idx` (`user_id` ASC),
  INDEX `fk_favorite_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_favorite_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `motaflix`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `motaflix`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `motaflix`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motaflix`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `subscription_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_subscription1_idx` (`subscription_id` ASC),
  CONSTRAINT `fk_payment_subscription1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `motaflix`.`subscription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
