/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.motaflix.Screens;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;

/**
 *
 * @author thiag
 */
public class Home extends javax.swing.JFrame {

    
    public String START_PAGE  = "start";
    public String MEDIAS_PAGE  = "medias";
    public String USERS_PAGE  = "users";
    public String ACTORS_PAGE  = "actors";
    public String CATEGORIES_PAGE  = "categories";

    private CardLayout cLayout;

    /**
     * Creates new form Home
     */
    public Home() {

        initComponents();
        

        //carrega os paineis para serem mostrados dinâmicamente
        Start start = new Start();
        Users users = new Users(this);
        Medias medias = new Medias(this);
        Actors actors = new Actors(this);
        Categories categories = new Categories(this);

        
        //adiciona os painéis no painel principal
        mainPanel.add(MEDIAS_PAGE, medias);
        mainPanel.add(USERS_PAGE, users);
        mainPanel.add(START_PAGE, start);
        mainPanel.add(CATEGORIES_PAGE, categories);
        mainPanel.add(ACTORS_PAGE, actors);

        
        showPanel(START_PAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        cLayout = new CardLayout();
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuActors1 = new javax.swing.JMenu();
        jMenuUsers = new javax.swing.JMenu();
        jMenuMedias = new javax.swing.JMenu();
        jMenuCategories = new javax.swing.JMenu();
        jMenuActors = new javax.swing.JMenu();
        btnDarkMode = new javax.swing.JMenu();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotaFlix - Dashboard administrativa");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1200, 700));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(1100, 700));
        mainPanel.setMinimumSize(new java.awt.Dimension(1100, 700));
        mainPanel.setLayout(null);
        mainPanel.setLayout(cLayout);

        jMenuBar1.setToolTipText("");

        jMenuActors1.setText("Início");
        jMenuActors1.setBorderPainted(true);
        jMenuActors1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jMenuActors1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuActors1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuActors1);

        jMenuUsers.setText("Usuários");
        jMenuUsers.setFocusable(false);
        jMenuUsers.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jMenuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsersMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuUsers);
        jMenuUsers.getAccessibleContext().setAccessibleName("");
        jMenuUsers.getAccessibleContext().setAccessibleDescription("");

        jMenuMedias.setText("Mídias");
        jMenuMedias.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jMenuMedias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMediasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuMedias);

        jMenuCategories.setText("Categorias");
        jMenuCategories.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jMenuCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCategoriesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCategories);

        jMenuActors.setText("Atores");
        jMenuActors.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jMenuActors.setHideActionText(true);
        jMenuActors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuActorsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuActors);

        btnDarkMode.setText("Dark Mode");
        btnDarkMode.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnDarkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDarkModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnDarkMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMediasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMediasMouseClicked
        // TODO add your handling code here:
        showPanel(MEDIAS_PAGE);
    }//GEN-LAST:event_jMenuMediasMouseClicked

    private void jMenuActors1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuActors1MouseClicked
        // TODO add your handling code here:
        showPanel(START_PAGE);
    }//GEN-LAST:event_jMenuActors1MouseClicked

    private void jMenuActorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuActorsMouseClicked
        // TODO add your handling code here:
        showPanel(ACTORS_PAGE);
    }//GEN-LAST:event_jMenuActorsMouseClicked

    private void btnDarkModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDarkModeMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnDarkModeMouseClicked

    private void jMenuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsersMouseClicked
        // TODO add your handling code here:
        showPanel(USERS_PAGE);
    }//GEN-LAST:event_jMenuUsersMouseClicked

    private void jMenuCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCategoriesMouseClicked
        // TODO add your handling code here:
        showPanel(CATEGORIES_PAGE);
    }//GEN-LAST:event_jMenuCategoriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

//    void switchPanes() {;
//        System.out.println("teste");
//        if (isRedPaneVisible) {
//            System.out.println("teste is");
//            showYelloPane();
//        } else {
//            System.out.println("teste is not");
//            showStartPanel();
//        }
//    }

    
    void showPanel(String panel) {
        cLayout.show(mainPanel, panel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnDarkMode;
    private javax.swing.JMenu jMenuActors;
    private javax.swing.JMenu jMenuActors1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCategories;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jMenuMedias;
    private javax.swing.JMenu jMenuUsers;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
